### ISSUE TITLE
accessing images in subfolders (uploadPreset)

### ISSUE THREAD

**Issue by clairefro** [cloudinary/cloudinary-react#193]
The below component is able to access images in the top level Assets folder of my cloudinary account, for example, `sample`

I've tried adding the prop `uploadPreset` to the as I saw it in one of the examples in this repo, but notice there is no uploadPreset in the API. How can I render images from folder `foo`?

```ts
export const ImageDisplay: FC<Props> = ({
  cloudinaryPublicId,
  gravity = "center",
  width = "100%",
  height = "100%",
  radius = "0",
  className,
}) => {

    return (
      <div className={"overflow-hidden " + className || ""}>
        <CloudinaryContext
          cloudName={process.env.CLOUDINARY_CLOUD_NAME}
        >
          <Image publicId={cloudinaryPublicId}>
            <Transformation width={width} height={height} gravity={gravity} radius={radius} />
          </Image>
        </CloudinaryContext>
      </div>
    );
  }
};
```

**Comment by eyalktCloudinary** [comment]
Hey @clairefro thanks for reaching out!

In Cloudinary, the public ID of an asset consists of the asset's path (folder) concatinated with the asset's name.
For instance, if you have an image named `elephant` and it resides in the `animals` folder of your account, then its public ID is `animals/elephant`.

This means that you do not need any additional parameters in order to render images that reside in a folder.

The `uploadPreset` is a parameter of the upload API, and is not related to the rendering of the images.
Additional information can be found here - 
https://cloudinary.com/documentation/upload_presets
https://cloudinary.com/documentation/image_upload_api_reference#required_parameters

**Comment by clairefro** [comment]
Thank you! I was confused because my presets were creating subdirectories and thought they were related. This clarifies things.
