### ISSUE TITLE
Issue with versioning URL and On-Demand Download from S3 Bucket

### ISSUE THREAD

**Issue by verystack** [cloudinary/cloudinary-react#211]
## Describe the bug in a sentence or two.
'/v1/' link suffix in DOM output of Image component does not result in lazy upload via S3 on server-side.

## Describe the desired/expected behavior
'/v1/' should be able to perform lazy upload to Cloudinary from S3, just as links without '/v1/' do. It is important to note, that if the image has already imported to Cloudinary (via a normal link), the '/v1/' path works fine - meaning it is an issue with the lazy upload via S3.

## Link to reproduction of the issue on codepen/jsfiddle/etc.
_As Example_
This file url references a new file (not yet imported to Cloudinary), as created by the <Image> component: https://res.cloudinary.com/audal-exclusives/image/upload/v1/media/eb8a3977-6edd-4a7d-8db3-50e4b59aa53e
If you visit this url, it won't work.

If you remove the '/v1/', it will work (as expected).
https://res.cloudinary.com/audal-exclusives/image/upload/media/eb8a3977-6edd-4a7d-8db3-50e4b59aa53e

After you visit the link without '/v1/' once, the link with the '/v1/' will also work.
https://res.cloudinary.com/audal-exclusives/image/upload/v1/media/eb8a3977-6edd-4a7d-8db3-50e4b59aa53e

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] UI/Performance - Display or performance issues
[X] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
1. Upload new file to S3 Bucket
2. Visit Cloudinary link that uploads from S3 Bucket on-demand (with the React Component).
3. 404

## Versions and Libraries (fill in the version numbers)
Cloudinary-react - 1.6.8
React - 16.10.2
Create-React-App - N/A
Node - 12.18.1
NPM - 6.14.5

**Comment by igy** [comment]
Hi,

Thanks for providing the details above. I've had a look at the example you provided and it's not related directly to either the React SDK/component, or the URL format (i.e whether the URL contains /v1/, the full version string, or not version string) - there's no functionality difference regarding the auto-upload feature based on the version component in the URL that you request from Cloudinary.

That said, it may appear that way due to how different URLs are cached differently in the CDN. Specifically in this case, the first request I see in our logs for `media/eb8a3977-6edd-4a7d-8db3-50e4b59aa53e` c

**Comment by igy** [comment]
Hi,

Thanks for providing the details above. 

I've had a look at the example you provided and it's not related directly to either the React SDK/component, or the URL format (i.e whether the URL contains /v1/, the full version string, or not version string). 

There's no functionality difference with how the [auto-upload feature](https://cloudinary.com/documentation/fetch_remote_images#auto_upload_remote_resources) woks with or without the version component in the URL that you requested from Cloudinary, though in cases where the auto-upload fails, it may appear that way due to how different URLs are cached differently in the CDN. 

Specifically in this case, the first request that I see in our logs for `media/eb8a3977-6edd-4a7d-8db3-50e4b59aa53e` contained /v1/ in the path, and that request triggered the auto-upload mapping, but when we requested the remote file, we received a 404 error for `s3://<your bucket name>/eb8a3977-6edd-4a7d-8db3-50e4b59aa53e` (I removed the bucket name for privacy reasons).

A later request about 13 minutes later for the same URL also triggered the mapping, but this time when we requested the file from your bucket, it succeeded. Once the file was added to your account, all new requests for that file worked, though you may have seen a cached 404 in your browser or our CDN for a while afterward if your request was that first request that failed.

To avoid this place completely, you can either upload the file explicitly to Cloudinary before it's requested, or ensure that the first request for the file will be able to retrieve the file from your S3. 

In this example I think the most likely explanation is that the first request we received was before the file was added to your S3 - If it helps you to track this down, the first (404) request I see was at 16:37:27 (UTC), and the first successful request was at 16:50:37

Please let me know if that helps and if there's anything else I can help with.

**Comment by verystack** [comment]
Will provide video showing phenomenon. The /v1/ 404s to the S3 bucket for ~20min, but accessing directly without /v1/ works instantly. Asset is available in S3 before each access (obviously). I wouldn’t be filing a Github issue without checking these basics.

**Comment by igy** [comment]
Thanks; please follow up on the ticket you gave open in our support system if you'll be sharing any account-specific information. It sounds like you're seeing a cached 404 on the /v1/ URL because the first request failed [due to the failed attempt by us to retrieve the image from your bucket], and that a request without the /v1/ is bypassing that cache and works as expected, but if you have an example that looks like it may have a different cause please do let us know

**Comment by igy** [comment]
Hi again,

I believe this is now resolved so I'm going to close this issue from hitgub, but if you're still seeing any issue with the auto upload mechanism, please let us know via our support site at https://support.cloudinary.com/hc/en-us/requests/new and we'll check it for you right away

Thanks,
Stephen
