### ISSUE TITLE
Getting tags with images

### ISSUE THREAD

**Issue by feruz111** [cloudinary/cloudinary-react#247]
Hi, 

Is it possible to get images with tags, (maybe with asset list) or this feature doesn't exist

Thanks

**Comment by PixelCook** [comment]
Hey there, 

You can either use the Node SDK if you would like to stick with an SDK, otherwise you can always fetch from the API. https://cloudinary.com/documentation/admin_api#tags Just reference the curl example, and if you are unfamiliar with converting curls to fetches you can always use a third-party tool like -https://kigiri.github.io/fetch/. 

I hope this helps! 
Thanks

**Comment by feruz111** [comment]
Ok thanks, but this api doesn’t work inside react does it?

**Comment by feruz111** [comment]
Thanks a lot for help

**Comment by esguerrat** [comment]
Hi there, 

If you need this in your front-end code, you could use the [client-side asset list](https://cloudinary.com/documentation/advanced_url_delivery_options#client_side_asset_lists) feature. You would need to apply a common tag to each file that you want to be returned. The client-side asset list returns a .JSON file with the basic details of all images tagged with a specific tag. You may need to enable this option in your account settings; there are instructions on that documentation page explaining how to do so.

Let us know if you have any questions.
