### ISSUE TITLE
not working with React 19

### ISSUE THREAD

**Issue by denka** [cloudinary/cloudinary-react#264]
getting this error when trying to use with react 19

```
Uncaught Error: A React Element from an older version of React was rendered. This is not supported. It can happen if:
- Multiple copies of the "react" package is used.
- A library pre-bundled an old copy of "react" or "react/jsx-runtime".
- A compiler tries to "inline" JSX instead of using the runtime.
```

**Comment by skalahasti-cloudinary** [comment]
Hi @denka ,

Thanks for your message.

I see that this error could be because of conflicting versions of react components in your application. 
Can you please try to add the conflicting packages to peerDependencies (and remove them from dependencies or devDependencies.). ?

This link could be helpful: 
https://stackoverflow.com/questions/66488492/solve-having-more-than-one-copy-of-react-in-the-same-app

Thanks,
Sree
