### ISSUE TITLE
Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by 416serg** [cloudinary/cloudinary-react#44]
If I have the following, the error occurs. 

```
  render() {
    const { loading, ruutById } = this.props;
    if (loading) return null;
    return <div className="EmbedRuut">
      <Image cloudName="ruutly" publicId={ruutById.backgroundImage}>
        <Transformation fetchFormat="auto" width="700" crop="scale"/>
      </Image>
      {ruutById.title}
    </div>;
  }
```

If I take out `<Transformation />`, the error goes away and the image loads but I'd like to perform some transformations on it (fetchFormat, qualityFormat, width, etc)

Also, would love to see an image lazy load example - I think it has the capacity to load up multiple "sizes" and then render them when they download.

**Comment by bernharduw** [comment]
I had this issue before (#31), it should be fixed by updating to the latest version 1.0.6, but I haven't tested yet. It occurs with React 16 only.

If you can't update, you can also work around this error by putting all the transformation props to the Image component:

    <Image cloudName="ruutly" publicId={ruutById.backgroundImage} fetchFormat="auto" width="700" crop="scale"/>

**Comment by eitanp461** [comment]
@416serg as pointed out by @bernharduw the issue should be fixed with version 1.0.6 of the SDK.

Re lazy load example, can you provide more details? 
"sizes" is a term related to responsive images. You can find more details about it here -
 https://cloudinary.com/blog/responsive_images_with_srcset_sizes_and_cloudinary

**Comment by eitanp461** [comment]
@416serg quality attribute name is simply `quality`, e.g.
```
          <Image publicId="sample" fetchFormat="auto" quality="auto">
            <Transformation height="150" width="150" crop="fill" effect="sepia" radius="20" />
          </Image>
```

As for responsive images, our SDK supports the `responsive` attribute, as well as additional attributes that optimize the viewing experience, see more details here - https://cloudinary.com/documentation/react_image_manipulation#responsive_image_settings

**Comment by 416serg** [comment]
@eitanp461 thanks for the note!

Like I said, the issue I am trying to address is being able to load a small image as a blurry placeholder while the bigger image gets loaded and replaces the small one when it's loaded - to increase performance of the page load while giving a progressive loading experience like a "blur-up"

**Comment by bernharduw** [comment]
@416serg is it possible for your case that you inline the blurry image so you don't need another network request? If not, would using progressive JPEGs be a viable option? https://support.cloudinary.com/hc/en-us/articles/202520682-Can-I-generate-Progressive-JPEGs-with-Cloudinary-

I like the progessive blur effect of e.g. Medium for large-sized images, and I think you can create a custom component quite easily with the help of cloudinary, but often this leads to more network requests and complexity only for an effect, not to actually improve the user experience.

I might be completely wrong though, because I don't know your actual use case. All I want to say is: with power comes responsibility ;-)

**Comment by 416serg** [comment]
@bernharduw thanks!

**Comment by bernharduw** [comment]
Hey @416serg you might use this component: https://github.com/FormidableLabs/react-progressive-image
