### ISSUE TITLE
Using `cloudinary-react` with `data-src` instead of `src`

### ISSUE THREAD

**Issue by chicgeek** [cloudinary/cloudinary-react#79]
## Question / feature request
Is it possible to set the src value in a `data-src` (or otherwise customisable) attribute instead of `src` when using the `<Image />` component?

## Context
I am using `cloudinary-react` in conjunction with [`react-id-swiper`](https://github.com/kidjp85/react-id-swiper). To take advantage of the lazyloading functionality packaged in the slider (only load images when the slide is requested), I would like to use a data attribute to store the URL for Cloudinary images.

## Alternatives
Is there a way to return the resultUrl from the package so I can inject it in a new element of my own? Otherwise, any other ideas before I create a manual srcset for this?

**Comment by strausr** [comment]
@chicgeek it seems that this issue was resolved internally but in case anyone else is looking at this. We are already using data-src for internal uses by the JS SDK responsive mechanism, and overloading it with additional meaning will cause conflicts.

The following is an example that uses our code SDK for creating responsive images using the carousel mentioned below.
It uses our API for creating the transformation and a responsive "srcset" attribute.

You can check it out here - https://codesandbox.io/s/0y8yx5vjpp

**Comment by chicgeek** [comment]
Thanks @strausr. 

For others who come later, it does seem that it's not possible to achieve this using specifically `cloudinary-react`, but an alternative method using the core module is the in the sandbox link posted above.
